name: Deploy to S3

on:
     push:
        branches:
            - main
        paths:
            - "web/**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.2.1
              with:
                  aws-region: "us-east-1"
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            - name: Sync files to S3
              run: |
                aws s3 sync ./web s3://${{ secrets.AWS_S3_BUCKET }} --delete

            - name: Create CloudFront invalidation
              run: |
                aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
               